# Generated by Django 3.1.5 on 2021-01-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=100),
            preserve_default=False,
        ),
    ]
